#
# Docker Compose for local test
#
version: "3"
services:
  jenkins-master:
    container_name: jenkins-master
    image: jenkins/jenkins:lts-jdk11
    ports:
      - 8080:8080
      - 50000:50000
    restart: always
    volumes:
    - ~/infra/jenkins_master:/var/jenkins_home
    environment:
      TZ: "America/New_York"
